### PR TITLE
Update TeleportUtils.java

### LINKED ISSUE #69: TeleportUtils.teleportPlayerInterdimentional conflicts with BetterPortals
1.12.2
https://github.com/Johni0702/BetterPortals/issues/455 (only the DE part, the Mining World issue looks unrelated to me)
```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Third-party transfer but not all views have been disposed of!
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Third-party transfer but not all views have been disposed of!
    at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.updateActiveViews(ServerWorldsManagerImpl.kt:70)
    at net.minecraft.server.management.PlayerChunkMap.handler$addPlayerWithViews$zei000(PlayerChunkMap.java:745)
    at net.minecraft.server.management.PlayerChunkMap.addPlayer(PlayerChunkMap.java)
    at net.minecraft.server.management.PlayerList.preparePlayer(PlayerList.java:290)
    at com.brandon3055.brandonscore.lib.TeleportUtils.teleportPlayerInterdimentional(TeleportUtils.java:169)
    at com.brandon3055.brandonscore.lib.TeleportUtils.handleEntityTeleport(TeleportUtils.java:87)
    at com.brandon3055.brandonscore.lib.TeleportUtils.teleportEntity(TeleportUtils.java:47)
    at com.brandon3055.brandonscore.utils.Teleporter$TeleportLocation.teleport(Teleporter.java:145)
    at com.brandon3055.draconicevolution.network.PacketDislocator$Handler.handleMessage(PacketDislocator.java:221)
    at com.brandon3055.draconicevolution.network.PacketDislocator$Handler.handleMessage(PacketDislocator.java:129)
    at com.brandon3055.brandonscore.network.MessageHandlerWrapper$1.run(MessageHandlerWrapper.java:19)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
```

For an explanation see https://github.com/DimensionalDevelopment/DimDoors/issues/130 it's basically the same issue except the offending method in DE is called `teleportPlayerInterdimentional`.

### PR DESCRIPTION
**Pull request by FreezePhoenix**
Fixes and closes #69

### CODE REVIEW

**Comment by brandon3055** [comment]
`changeDimension` uses the default vanilla teleporter for the dimension you are transferring to. If I'm not mistaken this means it will automatically generate portals when traveling between the overworld and the nether for example. Please correct me if I'm wronte.

**Comment by FreezePhoenix** [comment]
That is incorrect. Just tested, with an advanced dislocator between nether and overworld, and it didn't generate a nether portal.

**Comment by FreezePhoenix** [comment]
Latest commit removes generation of portals and obsidian platforms.

**Comment by brandon3055** [comment]
So one of the primary reasons I created my fully custom teleport system was the vanilla teleporter system was a mess and horrible to implement in the way I wanted. But it's since been improved by a forge PR so it's not so bad these days. I looked into it and there are still a few things I don't like about it but I was able to come up with something I am happy with. You were on the right track but there were just a few issues with your PR (and my own code) that were easier to just fix myself.

**Pull request closed without merging**
